services:
  postgres:
    image: postgres:16-alpine
    container_name: lingo-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - lingo_pgdata:/var/lib/postgresql/data
  libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: lingo-libretranslate
    ports:
      - "5000:5000"
    environment:
      - LT_LOAD_ONLY=es,en,ro,fr,de,it,pt


volumes:
  lingo_pgdata: